version: '3.8'

services:
  # Single-node Kafka in KRaft mode
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qo'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # --- CRITICAL FIXES FOR SINGLE NODE ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 5s
      timeout: 10s
      retries: 5

  # Single Database container
  postgres-db:
    image: postgres:18-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Event Service
  event-service:
    build: ./event-service
    container_name: event-service
    depends_on:
      postgres-db:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@postgres-db:5432/event_db
      KAFKA_BROKER: kafka:9092
    ports:
      - "8080:8080"

  # Registration Service
  registration-service:
    build: ./registration-service
    container_name: registration-service
    depends_on:
      postgres-db:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@postgres-db:5432/reg_db
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"
    restart: always

  # Payment Service
  payment-service:
    build: ./payment-service
    container_name: payment-service
    depends_on:
      postgres-db:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@postgres-db:5432/payment_db
      KAFKA_BROKER: kafka:9092
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    ports:
      - "8082:8082"